/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinIdRouteImport } from './routes/join.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthMeetingsIndexRouteImport } from './routes/_auth/meetings/index'
import { Route as AuthMeetingTypesIndexRouteImport } from './routes/_auth/meeting-types/index'
import { Route as AuthAgentsIndexRouteImport } from './routes/_auth/agents/index'
import { Route as AuthMeetingsNewRouteImport } from './routes/_auth/meetings/new'
import { Route as AuthMeetingsIdRouteImport } from './routes/_auth/meetings/$id'
import { Route as AuthMeetingTypesNewRouteImport } from './routes/_auth/meeting-types/new'
import { Route as AuthMeetingTypesIdRouteImport } from './routes/_auth/meeting-types/$id'
import { Route as AuthInvitesTokenRouteImport } from './routes/_auth/invites/$token'
import { Route as AuthAgentsNewRouteImport } from './routes/_auth/agents/new'
import { Route as AuthAgentsIdRouteImport } from './routes/_auth/agents/$id'
import { Route as AuthMeetingsIdIndexRouteImport } from './routes/_auth/meetings/$id/index'
import { Route as AuthMeetingsIdSummaryRouteImport } from './routes/_auth/meetings/$id/summary'
import { Route as AuthMeetingsIdRoomRouteImport } from './routes/_auth/meetings/$id/room'
import { Route as AuthMeetingsIdInsightsRouteImport } from './routes/_auth/meetings/$id/insights'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIdRoute = JoinIdRouteImport.update({
  id: '/join/$id',
  path: '/join/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMeetingsIndexRoute = AuthMeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMeetingTypesIndexRoute = AuthMeetingTypesIndexRouteImport.update({
  id: '/meeting-types/',
  path: '/meeting-types/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsIndexRoute = AuthAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMeetingsNewRoute = AuthMeetingsNewRouteImport.update({
  id: '/meetings/new',
  path: '/meetings/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMeetingsIdRoute = AuthMeetingsIdRouteImport.update({
  id: '/meetings/$id',
  path: '/meetings/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMeetingTypesNewRoute = AuthMeetingTypesNewRouteImport.update({
  id: '/meeting-types/new',
  path: '/meeting-types/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMeetingTypesIdRoute = AuthMeetingTypesIdRouteImport.update({
  id: '/meeting-types/$id',
  path: '/meeting-types/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvitesTokenRoute = AuthInvitesTokenRouteImport.update({
  id: '/invites/$token',
  path: '/invites/$token',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsNewRoute = AuthAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsIdRoute = AuthAgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMeetingsIdIndexRoute = AuthMeetingsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthMeetingsIdRoute,
} as any)
const AuthMeetingsIdSummaryRoute = AuthMeetingsIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AuthMeetingsIdRoute,
} as any)
const AuthMeetingsIdRoomRoute = AuthMeetingsIdRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => AuthMeetingsIdRoute,
} as any)
const AuthMeetingsIdInsightsRoute = AuthMeetingsIdInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthMeetingsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$id': typeof JoinIdRoute
  '/agents/$id': typeof AuthAgentsIdRoute
  '/agents/new': typeof AuthAgentsNewRoute
  '/invites/$token': typeof AuthInvitesTokenRoute
  '/meeting-types/$id': typeof AuthMeetingTypesIdRoute
  '/meeting-types/new': typeof AuthMeetingTypesNewRoute
  '/meetings/$id': typeof AuthMeetingsIdRouteWithChildren
  '/meetings/new': typeof AuthMeetingsNewRoute
  '/agents/': typeof AuthAgentsIndexRoute
  '/meeting-types/': typeof AuthMeetingTypesIndexRoute
  '/meetings/': typeof AuthMeetingsIndexRoute
  '/meetings/$id/insights': typeof AuthMeetingsIdInsightsRoute
  '/meetings/$id/room': typeof AuthMeetingsIdRoomRoute
  '/meetings/$id/summary': typeof AuthMeetingsIdSummaryRoute
  '/meetings/$id/': typeof AuthMeetingsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$id': typeof JoinIdRoute
  '/agents/$id': typeof AuthAgentsIdRoute
  '/agents/new': typeof AuthAgentsNewRoute
  '/invites/$token': typeof AuthInvitesTokenRoute
  '/meeting-types/$id': typeof AuthMeetingTypesIdRoute
  '/meeting-types/new': typeof AuthMeetingTypesNewRoute
  '/meetings/new': typeof AuthMeetingsNewRoute
  '/agents': typeof AuthAgentsIndexRoute
  '/meeting-types': typeof AuthMeetingTypesIndexRoute
  '/meetings': typeof AuthMeetingsIndexRoute
  '/meetings/$id/insights': typeof AuthMeetingsIdInsightsRoute
  '/meetings/$id/room': typeof AuthMeetingsIdRoomRoute
  '/meetings/$id/summary': typeof AuthMeetingsIdSummaryRoute
  '/meetings/$id': typeof AuthMeetingsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$id': typeof JoinIdRoute
  '/_auth/agents/$id': typeof AuthAgentsIdRoute
  '/_auth/agents/new': typeof AuthAgentsNewRoute
  '/_auth/invites/$token': typeof AuthInvitesTokenRoute
  '/_auth/meeting-types/$id': typeof AuthMeetingTypesIdRoute
  '/_auth/meeting-types/new': typeof AuthMeetingTypesNewRoute
  '/_auth/meetings/$id': typeof AuthMeetingsIdRouteWithChildren
  '/_auth/meetings/new': typeof AuthMeetingsNewRoute
  '/_auth/agents/': typeof AuthAgentsIndexRoute
  '/_auth/meeting-types/': typeof AuthMeetingTypesIndexRoute
  '/_auth/meetings/': typeof AuthMeetingsIndexRoute
  '/_auth/meetings/$id/insights': typeof AuthMeetingsIdInsightsRoute
  '/_auth/meetings/$id/room': typeof AuthMeetingsIdRoomRoute
  '/_auth/meetings/$id/summary': typeof AuthMeetingsIdSummaryRoute
  '/_auth/meetings/$id/': typeof AuthMeetingsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/auth/callback'
    | '/join/$id'
    | '/agents/$id'
    | '/agents/new'
    | '/invites/$token'
    | '/meeting-types/$id'
    | '/meeting-types/new'
    | '/meetings/$id'
    | '/meetings/new'
    | '/agents/'
    | '/meeting-types/'
    | '/meetings/'
    | '/meetings/$id/insights'
    | '/meetings/$id/room'
    | '/meetings/$id/summary'
    | '/meetings/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/auth/callback'
    | '/join/$id'
    | '/agents/$id'
    | '/agents/new'
    | '/invites/$token'
    | '/meeting-types/$id'
    | '/meeting-types/new'
    | '/meetings/new'
    | '/agents'
    | '/meeting-types'
    | '/meetings'
    | '/meetings/$id/insights'
    | '/meetings/$id/room'
    | '/meetings/$id/summary'
    | '/meetings/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/dashboard'
    | '/auth/callback'
    | '/join/$id'
    | '/_auth/agents/$id'
    | '/_auth/agents/new'
    | '/_auth/invites/$token'
    | '/_auth/meeting-types/$id'
    | '/_auth/meeting-types/new'
    | '/_auth/meetings/$id'
    | '/_auth/meetings/new'
    | '/_auth/agents/'
    | '/_auth/meeting-types/'
    | '/_auth/meetings/'
    | '/_auth/meetings/$id/insights'
    | '/_auth/meetings/$id/room'
    | '/_auth/meetings/$id/summary'
    | '/_auth/meetings/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  JoinIdRoute: typeof JoinIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$id': {
      id: '/join/$id'
      path: '/join/$id'
      fullPath: '/join/$id'
      preLoaderRoute: typeof JoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/meetings/': {
      id: '/_auth/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof AuthMeetingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/meeting-types/': {
      id: '/_auth/meeting-types/'
      path: '/meeting-types'
      fullPath: '/meeting-types/'
      preLoaderRoute: typeof AuthMeetingTypesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/': {
      id: '/_auth/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthAgentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/meetings/new': {
      id: '/_auth/meetings/new'
      path: '/meetings/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof AuthMeetingsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/meetings/$id': {
      id: '/_auth/meetings/$id'
      path: '/meetings/$id'
      fullPath: '/meetings/$id'
      preLoaderRoute: typeof AuthMeetingsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/meeting-types/new': {
      id: '/_auth/meeting-types/new'
      path: '/meeting-types/new'
      fullPath: '/meeting-types/new'
      preLoaderRoute: typeof AuthMeetingTypesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/meeting-types/$id': {
      id: '/_auth/meeting-types/$id'
      path: '/meeting-types/$id'
      fullPath: '/meeting-types/$id'
      preLoaderRoute: typeof AuthMeetingTypesIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invites/$token': {
      id: '/_auth/invites/$token'
      path: '/invites/$token'
      fullPath: '/invites/$token'
      preLoaderRoute: typeof AuthInvitesTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/new': {
      id: '/_auth/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthAgentsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/$id': {
      id: '/_auth/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AuthAgentsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/meetings/$id/': {
      id: '/_auth/meetings/$id/'
      path: '/'
      fullPath: '/meetings/$id/'
      preLoaderRoute: typeof AuthMeetingsIdIndexRouteImport
      parentRoute: typeof AuthMeetingsIdRoute
    }
    '/_auth/meetings/$id/summary': {
      id: '/_auth/meetings/$id/summary'
      path: '/summary'
      fullPath: '/meetings/$id/summary'
      preLoaderRoute: typeof AuthMeetingsIdSummaryRouteImport
      parentRoute: typeof AuthMeetingsIdRoute
    }
    '/_auth/meetings/$id/room': {
      id: '/_auth/meetings/$id/room'
      path: '/room'
      fullPath: '/meetings/$id/room'
      preLoaderRoute: typeof AuthMeetingsIdRoomRouteImport
      parentRoute: typeof AuthMeetingsIdRoute
    }
    '/_auth/meetings/$id/insights': {
      id: '/_auth/meetings/$id/insights'
      path: '/insights'
      fullPath: '/meetings/$id/insights'
      preLoaderRoute: typeof AuthMeetingsIdInsightsRouteImport
      parentRoute: typeof AuthMeetingsIdRoute
    }
  }
}

interface AuthMeetingsIdRouteChildren {
  AuthMeetingsIdInsightsRoute: typeof AuthMeetingsIdInsightsRoute
  AuthMeetingsIdRoomRoute: typeof AuthMeetingsIdRoomRoute
  AuthMeetingsIdSummaryRoute: typeof AuthMeetingsIdSummaryRoute
  AuthMeetingsIdIndexRoute: typeof AuthMeetingsIdIndexRoute
}

const AuthMeetingsIdRouteChildren: AuthMeetingsIdRouteChildren = {
  AuthMeetingsIdInsightsRoute: AuthMeetingsIdInsightsRoute,
  AuthMeetingsIdRoomRoute: AuthMeetingsIdRoomRoute,
  AuthMeetingsIdSummaryRoute: AuthMeetingsIdSummaryRoute,
  AuthMeetingsIdIndexRoute: AuthMeetingsIdIndexRoute,
}

const AuthMeetingsIdRouteWithChildren = AuthMeetingsIdRoute._addFileChildren(
  AuthMeetingsIdRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthAgentsIdRoute: typeof AuthAgentsIdRoute
  AuthAgentsNewRoute: typeof AuthAgentsNewRoute
  AuthInvitesTokenRoute: typeof AuthInvitesTokenRoute
  AuthMeetingTypesIdRoute: typeof AuthMeetingTypesIdRoute
  AuthMeetingTypesNewRoute: typeof AuthMeetingTypesNewRoute
  AuthMeetingsIdRoute: typeof AuthMeetingsIdRouteWithChildren
  AuthMeetingsNewRoute: typeof AuthMeetingsNewRoute
  AuthAgentsIndexRoute: typeof AuthAgentsIndexRoute
  AuthMeetingTypesIndexRoute: typeof AuthMeetingTypesIndexRoute
  AuthMeetingsIndexRoute: typeof AuthMeetingsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthAgentsIdRoute: AuthAgentsIdRoute,
  AuthAgentsNewRoute: AuthAgentsNewRoute,
  AuthInvitesTokenRoute: AuthInvitesTokenRoute,
  AuthMeetingTypesIdRoute: AuthMeetingTypesIdRoute,
  AuthMeetingTypesNewRoute: AuthMeetingTypesNewRoute,
  AuthMeetingsIdRoute: AuthMeetingsIdRouteWithChildren,
  AuthMeetingsNewRoute: AuthMeetingsNewRoute,
  AuthAgentsIndexRoute: AuthAgentsIndexRoute,
  AuthMeetingTypesIndexRoute: AuthMeetingTypesIndexRoute,
  AuthMeetingsIndexRoute: AuthMeetingsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  JoinIdRoute: JoinIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
