#!/usr/bin/env bash
# MojoMeet dev/test bootstrap — generates .env with fresh secrets.
#
# Usage:
#   ./scripts/bootstrap.sh mysql://user:pass@host:3306/meeting_app [public_url]
#
# Arguments:
#   MYSQL_URL  (required)  connection string for a reachable MySQL 8.0.19+
#   PUBLIC_URL (optional)  the URL users will hit in the browser.
#                          Defaults to http://localhost. Use your server's
#                          public hostname or IP for non-local deploys,
#                          e.g. http://10.0.0.5 or http://meet.example.com

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"
LIVEKIT_CONFIG_FILE="$ROOT/livekit/livekit.yaml"

if [[ -f "$ENV_FILE" ]]; then
  echo "✗ $ENV_FILE already exists — refusing to overwrite."
  echo "  Delete it first if you really want to regenerate secrets."
  exit 1
fi

MYSQL_URL="${1:-}"
if [[ -z "$MYSQL_URL" ]]; then
  echo "✗ MYSQL_URL is required as the first argument."
  echo "  Example: ./scripts/bootstrap.sh mysql://root:pass@host:3306/meeting_app"
  exit 1
fi

PUBLIC_URL="${2:-http://localhost}"

# Generate secrets — openssl is available on every modern Linux/macOS host.
JWT_SECRET=$(openssl rand -hex 32)
INTERNAL_API_KEY=$(openssl rand -hex 32)
LIVEKIT_API_KEY="APIM$(openssl rand -hex 6)"
LIVEKIT_API_SECRET=$(openssl rand -hex 32)

# LiveKit URL the BROWSER uses. Points at the LiveKit container's published port
# on the host. The api + worker containers use ws://livekit:7880 internally
# (set in docker-compose.yml) — that side is not user-configurable.
# Strip scheme, trailing slash, and any :port so we don't end up with ws://host:5173:7880.
LIVEKIT_HOST="$(echo "$PUBLIC_URL" | sed -E 's|^https?://||; s|/$||; s|:[0-9]+$||')"
LIVEKIT_URL_PUBLIC="ws://${LIVEKIT_HOST}:7880"

cat > "$ENV_FILE" <<EOF
# ─── Generated by scripts/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) ───
# Keep this file out of git. Delete + re-run bootstrap to rotate secrets.

# Public URL the browser uses to hit the web app (used for CORS allowlist,
# OAuth redirects, email links). No trailing slash.
PUBLIC_URL=$PUBLIC_URL

# Port the web container publishes on the host. 5173 by default so this stack
# coexists with an upstream reverse proxy (Forge/Caddy/Traefik) already owning
# :80. The upstream then proxies to 127.0.0.1:5173. Change to 80 for a pure
# standalone deploy.
WEB_PORT=5173

# Database — supplied at bootstrap time
MYSQL_URL=$MYSQL_URL

# API secrets — regenerated on each bootstrap run
JWT_SECRET=$JWT_SECRET
INTERNAL_API_KEY=$INTERNAL_API_KEY

# LiveKit — self-hosted via docker-compose
# LIVEKIT_URL_PUBLIC is the URL the browser dials (host:7880). Server-side
# containers use ws://livekit:7880 (set directly in docker-compose.yml).
LIVEKIT_URL_PUBLIC=$LIVEKIT_URL_PUBLIC
LIVEKIT_API_KEY=$LIVEKIT_API_KEY
LIVEKIT_API_SECRET=$LIVEKIT_API_SECRET

# ─── Fill these in manually before \`docker compose up\` ───────────────

# LLM providers (at least one required for the worker to produce insights)
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
DEFAULT_LLM_PROVIDER=openai
DEFAULT_LLM_MODEL=gpt-4o-mini

# Google OAuth (optional — leave blank to disable Google sign-in)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=$PUBLIC_URL/api/v0/auth/google/callback

# SMTP (optional — leave blank to disable email; features degrade gracefully)
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=MojoMeet <noreply@localhost>
EOF

chmod 600 "$ENV_FILE"

# ─── LiveKit config ─────────────────────────────────────────────────
# LiveKit takes its `keys` map from a YAML file; env-var config is flaky
# for map types. Write the real secrets into livekit/livekit.yaml.
mkdir -p "$ROOT/livekit"
cat > "$LIVEKIT_CONFIG_FILE" <<EOF
port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50099
  use_external_ip: true
keys:
  $LIVEKIT_API_KEY: $LIVEKIT_API_SECRET
logging:
  level: info
EOF

chmod 600 "$LIVEKIT_CONFIG_FILE"

echo "✓ Generated $ENV_FILE"
echo "✓ Generated $LIVEKIT_CONFIG_FILE"
echo ""
echo "Next steps:"
echo "  1. (Optional) Edit .env to add OPENAI_API_KEY / SMTP / OAuth values."
echo "  2. docker compose up -d --build"
echo "  3. Open $PUBLIC_URL"
echo ""
echo "Generated LiveKit API key (for reference): $LIVEKIT_API_KEY"
